version: '2'

services:
  api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    volumes:
      - ./docs:/usr/src/app/docs
      - ./tests:/usr/src/app/tests
      - ./web:/usr/src/app/web
      - ./setup.py:/usr/src/app/setup.py
    env_file:
      - .env
    environment:
      API_HOST: api
      BDB_NODE_HOST: bigchaindb
      BDB_NODE_PORT: 9984
    ports:
      - "${API_PORT}:3000"
    command: python web/server.py
  mdb:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod --replSet=bigchain-rs
  bigchaindb:
    build: ./compose/bigchaindb
    env_file:
      - .env
    environment:
      BIGCHAINDB_DATABASE_BACKEND: mongodb
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
    ports:
      - "9984"
    command: bigchaindb start
